name: resavation
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_credit_card: ^3.0.1
  logger: ^1.1.0
  flutter:
    sdk: flutter
  
  # state_managment
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  flutter_hooks: ^0.18.2
  observable_ish: ^3.0.1

  # network
  permission_handler: ^8.3.0
  location: ^4.3.0
  google_maps_flutter: ^2.1.3
  dio: ^4.0.5
  retrofit: ^3.0.1+1
  analyzer: ^3.4.1
  json_serializable: ^6.1.5
  flutter_polyline_points: ^1.0.0

  # ui
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  flutter_svg: ^1.0.0
  dots_indicator: ^2.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  agora_rtc_engine: ^5.0.0
  flutter_paystack: ^1.0.5+1
  iconsax: ^0.0.8
  country_picker: ^2.0.12
  date_ranger: ^0.0.1
  dropdown_button2: ^1.2.2
  emoji_picker_flutter: ^1.1.2
  carousel_slider: ^4.0.0
  unicons: ^2.1.0
  syncfusion_flutter_datepicker: ^19.4.56
  image_picker: ^0.8.4+11
  intl_phone_number_input: ^0.7.0+2
  badges: ^2.0.2




dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  stacked_generator: ^0.5.6
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/resavation_logo.png"

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/placeholders/