name: resavation
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^5.2.0
  analyzer: ^3.4.1
<<<<<<< HEAD
=======

>>>>>>> test
  animations: ^2.0.2
  badges: ^2.0.2
  built_value: ^8.1.3
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.0
  country_code_picker: ^2.0.2
  country_picker: ^2.0.12
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  date_ranger: ^0.0.1
  dio: ^4.0.5
  dots_indicator: ^2.0.0
  dropdown_button2: ^1.2.2
  emoji_picker_flutter: ^1.1.2
  file_picker: ^4.5.1
  firebase_core: ^1.10.0
  firebase_storage: ^10.2.10
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.1
  flutter_hooks: ^0.18.2
  flutter_inappwebview: ^5.4.3+7
  flutter_paystack: ^1.0.5+1
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.0.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.3
  iconsax: ^0.0.8
  image_picker: ^0.8.4+11
  intl_phone_number_input: ^0.7.0+2
  jwt_decoder: ^2.0.1
  location: ^4.3.0
  logger: ^1.1.0
  multi_select_flutter: ^4.1.2
  observable_ish: ^4.0.4
  open_file: ^3.2.1
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  pinput: ^2.2.7
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  snippet_coder_utils: ^1.0.12
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  syncfusion_flutter_datepicker: ^20.1.55
  unicons: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.8
  built_value_generator: ^8.1.3
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  stacked_generator: ^0.6.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/resavation_logo.png"

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/placeholders/
