name: resavation
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_credit_card: ^3.0.1
  logger: ^1.1.0
  flutter:
    sdk: flutter
  
  # state_managment
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  flutter_hooks: ^0.18.2

  # ui
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  flutter_svg: ^1.0.0
  dots_indicator: ^2.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  agora_rtc_engine: ^5.0.0
  permission_handler: ^8.3.0
  flutter_paystack: ^1.0.5+1
  iconsax: ^0.0.8
  country_picker: ^2.0.12
  date_ranger: ^0.0.1
  google_maps_flutter: ^2.1.3
  dropdown_button2: ^1.2.2
  location: ^4.3.0
  emoji_picker_flutter: ^1.1.2
  carousel_slider: ^4.0.0
  unicons: ^2.1.0



dev_dependencies:
  stacked_generator: ^0.5.6
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/placeholders/