name: resavation
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  country_code_picker: ^2.0.2
  flutter_credit_card: ^3.0.1
  logger: ^1.1.0
  flutter:
    sdk: flutter
  
  # state_managment
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  flutter_hooks: ^0.18.2
  observable_ish: ^4.0.4
  # network
  permission_handler: ^9.2.0
  location: ^4.3.0
  google_maps_flutter: ^2.1.3
  dio: ^4.0.5
  built_value: ^8.1.3
  analyzer: ^3.4.1
  flutter_polyline_points: ^1.0.0

  # ui
  country_picker: ^2.0.12
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  flutter_svg: ^1.0.0
  dots_indicator: ^2.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  agora_rtc_engine: ^5.1.1
  flutter_paystack: ^1.0.5+1
  iconsax: ^0.0.8
  date_ranger: ^0.0.1
  dropdown_button2: ^1.2.2
  emoji_picker_flutter: ^1.1.2
  carousel_slider: ^4.0.0
  unicons: ^2.1.0
  syncfusion_flutter_datepicker: ^20.1.55
  image_picker: ^0.8.4+11
  intl_phone_number_input: ^0.7.0+2
  badges: ^2.0.2
  file_picker: ^4.5.1
  open_file: ^3.2.1
  pinput: ^2.2.7
  firebase_core: ^1.10.0
  firebase_storage: ^10.2.10
  cloud_firestore: ^3.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.13
  photo_view: ^0.13.0



dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  stacked_generator: ^0.6.2
  json_serializable: ^6.1.1
  built_value_generator: ^8.1.3
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/resavation_logo.png"

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/placeholders/