name: resavation
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^5.2.0
  analyzer: ^3.4.1
  animations: ^2.0.2
  badges: ^2.0.2
  built_value: ^8.1.3
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.4.0
  country_picker: ^2.0.12
  cupertino_icons: ^1.0.2
  dio: ^4.0.5
  dropdown_button2: ^1.2.2
  emoji_picker_flutter: ^1.1.2
  file_picker: ^4.5.1
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3
  flutter:
    sdk: flutter
  flutter_dojah_financial: ^0.1.5
  flutter_hooks: ^0.18.2
  flutter_paystack: ^1.0.5+1
  flutter_polyline_points: ^1.0.0
  flutter_ringtone_player: ^3.2.0
  flutter_svg: ^1.0.0
  focus_detector: ^2.0.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.3
  image_picker: ^0.8.4+11
  jwt_decoder: ^2.0.1
  logger: ^1.1.0
  observable_ish: ^4.0.4
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  pinput: ^2.2.7
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16

dev_dependencies:
  build_runner: ^2.1.8
  built_value_generator: ^8.1.3
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  stacked_generator: ^0.6.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/new_app_icon.png"

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/placeholders/
